// ST12 runtime-migration value-matrix driver (assertion #3b, value leg).
//
// Generic case runner: reads uid<TAB>key<TAB>want<TAB>why lines from a cases
// file and asserts each GetConfig answer through the real Go SDK. The cases
// files are GENERATED by server/runtime_migration.sh from server-observed
// state (anchor file + key-holders + versions API) — nothing here re-derives
// an expectation from the hash rule, so a wrong server answer cannot be
// mirrored by a wrong expectation (README non-degeneracy #4).
//
// `<DEFAULT>` in the want column means "the SDK must fall through to the
// caller default": the fixture's exp_key has NO full release, so a uid outside
// E_mig resolves it to the default argument. That is what makes the sliced
// uids' value SWITCH observable — default before migrate-out, the experiment
// version after, default again after migrate-in.
//
// HTTP transport only, deliberately: assertion #2 already proves all three
// SDKs x both transports resolve identically; the increment tested here is
// the SERVER's bucketing response to a topology move, one SDK observation of
// it suffices (README: "server-only by mechanism").
package main

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"os"
	"strings"
	"time"

	tac "github.com/Lightspeed-Intelligence/tipsy-ab-config-sdk/sdk/go/tipsyabconfig"
)

// defaultSentinel is what the driver passes as the GetConfig default. It must
// never collide with a real fixture value (fixture values are EXP_A/EXP_B/
// MIG_LIVE*/LIVE_v*), otherwise "fell through to default" and "resolved a real
// value" become indistinguishable.
const defaultSentinel = "<RTMIG-DEFAULT-7f3a>"

func main() {
	httpBase := flag.String("http", "http://localhost:8081", "HTTP base")
	ns := flag.String("ns", "st9_combo", "namespace")
	casesPath := flag.String("cases", "", "cases file: uid<TAB>key<TAB>want<TAB>why (want <DEFAULT> = caller default)")
	label := flag.String("label", "rtmig", "phase label for output")
	flag.Parse()

	token := os.Getenv("AB_CONFIG_TOKEN")
	if token == "" {
		fmt.Fprintln(os.Stderr, "FATAL: AB_CONFIG_TOKEN required")
		os.Exit(2)
	}
	if *casesPath == "" {
		fmt.Fprintln(os.Stderr, "FATAL: --cases required")
		os.Exit(2)
	}

	type kase struct{ uid, key, want, why string }
	var cases []kase
	f, err := os.Open(*casesPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "FATAL: open cases: %v\n", err)
		os.Exit(2)
	}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimRight(sc.Text(), "\n")
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "\t", 4)
		if len(parts) < 3 {
			fmt.Fprintf(os.Stderr, "FATAL: malformed case line: %q\n", line)
			os.Exit(2)
		}
		why := ""
		if len(parts) == 4 {
			why = parts[3]
		}
		want := parts[2]
		if want == "<DEFAULT>" {
			want = defaultSentinel
		}
		cases = append(cases, kase{parts[0], parts[1], want, why})
	}
	f.Close()
	if len(cases) == 0 {
		fmt.Fprintln(os.Stderr, "FATAL: cases file is empty — an empty run proves nothing")
		os.Exit(2)
	}

	cfg := tac.Config{
		ConfigServiceAddr: *httpBase,
		AbtestServiceAddr: *httpBase,
		Transport:         "http",
		Token:             token,
		Namespaces:        []string{*ns},
		Logger:            slog.New(slog.NewTextHandler(io.Discard, nil)),
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cli, err := tac.Init(ctx, cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "FATAL: Init: %v\n", err)
		os.Exit(2)
	}
	defer cli.Close()
	if h := cli.Health(); h.StartupCacheEmpty {
		fmt.Fprintln(os.Stderr, "FATAL: startup cache empty")
		os.Exit(2)
	}

	pass, fail := 0, 0
	// Delta, not absolute — same reasoning as the #2 drivers: an ab→full
	// fallback DURING these calls would mean a value was delivered by the
	// fallback arm instead of the abtest main path, silently masking a wrong
	// bucketing verdict behind a correct-looking value.
	before := cli.Metrics().AbtestFallbackTotal(*ns)
	for _, c := range cases {
		rctx, rcancel := context.WithTimeout(context.Background(), 15*time.Second)
		abctx := cli.NewAbtestContext(rctx, c.uid, nil)
		got, err := cli.GetConfig(rctx, abctx, *ns, c.key, defaultSentinel)
		rcancel()
		switch {
		case err != nil:
			fmt.Printf("FAIL [%s] %s/%s err=%v\n", *label, c.uid, c.key, err)
			fail++
		case got != c.want:
			fmt.Printf("FAIL [%s] %-10s %-9s got=%-22q want=%-22q (%s)\n", *label, c.uid, c.key, got, c.want, c.why)
			fail++
		default:
			fmt.Printf("PASS [%s] %-10s %-9s = %-22q (%s)\n", *label, c.uid, c.key, got, c.why)
			pass++
		}
	}
	delta := cli.Metrics().AbtestFallbackTotal(*ns) - before
	if delta == 0 {
		fmt.Printf("PASS [%s] abtestFallback delta = 0\n", *label)
		pass++
	} else {
		fmt.Printf("FAIL [%s] abtestFallback delta = %d (values may be fallback-delivered)\n", *label, delta)
		fail++
	}

	total := pass + fail
	fmt.Printf("SUMMARY [%s]: pass=%d fail=%d of %d checks\n", *label, pass, fail, total)
	want := len(cases) + 1
	if total != want {
		fmt.Printf("OBSERVATION-COUNT MISMATCH [%s]: ran %d, expected %d\n", *label, total, want)
		os.Exit(1)
	}
	fmt.Printf("OBSERVATION-COUNT OK [%s] (%d expected)\n", *label, want)
	if fail > 0 {
		os.Exit(1)
	}
}
