# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tipsy_ab_config._proto.tipsy.abtest.v1 import abtest_pb2 as tipsy_dot_abtest_dot_v1_dot_abtest__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tipsy/abtest/v1/abtest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AbtestServiceStub(object):
    """AbtestService is the gRPC entry point for the abtest module (v2).

    - GetExperimentResult: business SDK ⇄ abtest. Given (namespace, user_id,
    user_attrs, layer_ids?, experiment_type, display_type) it walks the
    topology tree and returns the experiment / whitelist hits (+ optional
    gray hit list when display_type==EACH_EXPERIMENT_GROUP and
    experiment_type ∈ {CONFIG_VERSION, ALL}).
    - GetPossibleVersionsAndExperimentSnapshotSeq: config ⇄ abtest (unchanged).
    - GetExperimentSnapshotSeq: config ⇄ abtest. Lightweight "just the seq"
    read of namespace_experiment_snapshot_seq — returns only the int64 seq
    (no possibleVersions, no full-table scans) for config's snapshot-cache
    freshness check.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExperimentResult = channel.unary_unary(
                '/tipsy.abtest.v1.AbtestService/GetExperimentResult',
                request_serializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentResultRequest.SerializeToString,
                response_deserializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentResultResponse.FromString,
                _registered_method=True)
        self.GetPossibleVersionsAndExperimentSnapshotSeq = channel.unary_unary(
                '/tipsy.abtest.v1.AbtestService/GetPossibleVersionsAndExperimentSnapshotSeq',
                request_serializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetPossibleVersionsAndExperimentSnapshotSeqRequest.SerializeToString,
                response_deserializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetPossibleVersionsAndExperimentSnapshotSeqResponse.FromString,
                _registered_method=True)
        self.GetExperimentSnapshotSeq = channel.unary_unary(
                '/tipsy.abtest.v1.AbtestService/GetExperimentSnapshotSeq',
                request_serializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentSnapshotSeqRequest.SerializeToString,
                response_deserializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentSnapshotSeqResponse.FromString,
                _registered_method=True)


class AbtestServiceServicer(object):
    """AbtestService is the gRPC entry point for the abtest module (v2).

    - GetExperimentResult: business SDK ⇄ abtest. Given (namespace, user_id,
    user_attrs, layer_ids?, experiment_type, display_type) it walks the
    topology tree and returns the experiment / whitelist hits (+ optional
    gray hit list when display_type==EACH_EXPERIMENT_GROUP and
    experiment_type ∈ {CONFIG_VERSION, ALL}).
    - GetPossibleVersionsAndExperimentSnapshotSeq: config ⇄ abtest (unchanged).
    - GetExperimentSnapshotSeq: config ⇄ abtest. Lightweight "just the seq"
    read of namespace_experiment_snapshot_seq — returns only the int64 seq
    (no possibleVersions, no full-table scans) for config's snapshot-cache
    freshness check.
    """

    def GetExperimentResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPossibleVersionsAndExperimentSnapshotSeq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExperimentSnapshotSeq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AbtestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExperimentResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperimentResult,
                    request_deserializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentResultRequest.FromString,
                    response_serializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentResultResponse.SerializeToString,
            ),
            'GetPossibleVersionsAndExperimentSnapshotSeq': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPossibleVersionsAndExperimentSnapshotSeq,
                    request_deserializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetPossibleVersionsAndExperimentSnapshotSeqRequest.FromString,
                    response_serializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetPossibleVersionsAndExperimentSnapshotSeqResponse.SerializeToString,
            ),
            'GetExperimentSnapshotSeq': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExperimentSnapshotSeq,
                    request_deserializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentSnapshotSeqRequest.FromString,
                    response_serializer=tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentSnapshotSeqResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tipsy.abtest.v1.AbtestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tipsy.abtest.v1.AbtestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AbtestService(object):
    """AbtestService is the gRPC entry point for the abtest module (v2).

    - GetExperimentResult: business SDK ⇄ abtest. Given (namespace, user_id,
    user_attrs, layer_ids?, experiment_type, display_type) it walks the
    topology tree and returns the experiment / whitelist hits (+ optional
    gray hit list when display_type==EACH_EXPERIMENT_GROUP and
    experiment_type ∈ {CONFIG_VERSION, ALL}).
    - GetPossibleVersionsAndExperimentSnapshotSeq: config ⇄ abtest (unchanged).
    - GetExperimentSnapshotSeq: config ⇄ abtest. Lightweight "just the seq"
    read of namespace_experiment_snapshot_seq — returns only the int64 seq
    (no possibleVersions, no full-table scans) for config's snapshot-cache
    freshness check.
    """

    @staticmethod
    def GetExperimentResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.abtest.v1.AbtestService/GetExperimentResult',
            tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentResultRequest.SerializeToString,
            tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPossibleVersionsAndExperimentSnapshotSeq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.abtest.v1.AbtestService/GetPossibleVersionsAndExperimentSnapshotSeq',
            tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetPossibleVersionsAndExperimentSnapshotSeqRequest.SerializeToString,
            tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetPossibleVersionsAndExperimentSnapshotSeqResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExperimentSnapshotSeq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.abtest.v1.AbtestService/GetExperimentSnapshotSeq',
            tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentSnapshotSeqRequest.SerializeToString,
            tipsy_dot_abtest_dot_v1_dot_abtest__pb2.GetExperimentSnapshotSeqResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
