# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tipsy_ab_config._proto.tipsy.config.v1 import config_pb2 as tipsy_dot_config_dot_v1_dot_config__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tipsy/config/v1/config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigServiceStub(object):
    """ConfigService is the read entrypoint for business SDKs AND the abtest
    module. It carries:

    - PullAll / Subscribe:               business SDK ⇄ config (PullAll =
    synchronous full snapshot, Subscribe = server-streaming push of new
    snapshots when either business_snapshot_seq OR experiment_snapshot_seq
    advances).
    - ListNamespacesByKind / ListConfigKeys / ListConfigVersions: abtest
    module reads config metadata over gRPC (no cross-schema SQL).
    - NotifyBusinessNamespaceChange: abtest module signals config that an
    experiment / whitelist write happened ⇒ config bumps an in-memory
    experiment_snapshot_seq tracker, re-assembles the snapshot, pushes to
    local Subscribe streams, AND fans out NodeInternal.Notify to sibling
    config nodes. Fire-and-forget.

    See config-platform-backend.md §4.1 for the canonical contract; this proto
    is the source of truth for field tags and types.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullAll = channel.unary_unary(
                '/tipsy.config.v1.ConfigService/PullAll',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.PullAllRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.PullAllResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/tipsy.config.v1.ConfigService/Subscribe',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.ConfigUpdateEvent.FromString,
                _registered_method=True)
        self.ListNamespacesByKind = channel.unary_unary(
                '/tipsy.config.v1.ConfigService/ListNamespacesByKind',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListNamespacesByKindRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListNamespacesByKindResponse.FromString,
                _registered_method=True)
        self.ListConfigKeys = channel.unary_unary(
                '/tipsy.config.v1.ConfigService/ListConfigKeys',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigKeysRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigKeysResponse.FromString,
                _registered_method=True)
        self.ListConfigVersions = channel.unary_unary(
                '/tipsy.config.v1.ConfigService/ListConfigVersions',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigVersionsRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigVersionsResponse.FromString,
                _registered_method=True)
        self.NotifyBusinessNamespaceChange = channel.unary_unary(
                '/tipsy.config.v1.ConfigService/NotifyBusinessNamespaceChange',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.NotifyBusinessNamespaceChangeRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.NotifyBusinessNamespaceChangeResponse.FromString,
                _registered_method=True)
        self.GetDynamicConfig = channel.unary_unary(
                '/tipsy.config.v1.ConfigService/GetDynamicConfig',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetDynamicConfigRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetDynamicConfigResponse.FromString,
                _registered_method=True)
        self.GetStaticConfig = channel.unary_unary(
                '/tipsy.config.v1.ConfigService/GetStaticConfig',
                request_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetStaticConfigRequest.SerializeToString,
                response_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetStaticConfigResponse.FromString,
                _registered_method=True)


class ConfigServiceServicer(object):
    """ConfigService is the read entrypoint for business SDKs AND the abtest
    module. It carries:

    - PullAll / Subscribe:               business SDK ⇄ config (PullAll =
    synchronous full snapshot, Subscribe = server-streaming push of new
    snapshots when either business_snapshot_seq OR experiment_snapshot_seq
    advances).
    - ListNamespacesByKind / ListConfigKeys / ListConfigVersions: abtest
    module reads config metadata over gRPC (no cross-schema SQL).
    - NotifyBusinessNamespaceChange: abtest module signals config that an
    experiment / whitelist write happened ⇒ config bumps an in-memory
    experiment_snapshot_seq tracker, re-assembles the snapshot, pushes to
    local Subscribe streams, AND fans out NodeInternal.Notify to sibling
    config nodes. Fire-and-forget.

    See config-platform-backend.md §4.1 for the canonical contract; this proto
    is the source of truth for field tags and types.
    """

    def PullAll(self, request, context):
        """PullAll returns one NamespaceSnapshot per requested namespace. The
        snapshot assembly path joins release_full (config DB) with abtest's
        GetPossibleVersionsAndExperimentSnapshotSeq via gRPC; on abtest RPC
        failure config falls back to a degraded snapshot containing only
        full-release versions + experiment_snapshot_seq = 0.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe is a server-streaming push channel. The client declares the
        double seq pair it already has cached in known_seqs; the server emits a
        ConfigUpdateEvent (containing a fresh NamespaceSnapshot) on the initial
        connection for any ns that is stale, and again whenever EITHER seq
        advances for a subscribed ns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespacesByKind(self, request, context):
        """ListNamespacesByKind enumerates business namespaces (the only kind in
        v0.8) from namespace_registry. Used by abtest at startup + every 5s to
        discover new business ns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConfigKeys(self, request, context):
        """ListConfigKeys / ListConfigVersions feed the abtest console UI select
        panel and the application-level version-existence check abtest performs
        when writing experiments / whitelists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConfigVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyBusinessNamespaceChange(self, request, context):
        """NotifyBusinessNamespaceChange is invoked by abtest after every write
        that may change "possible versions" for that ns (start / pause / resume
        / complete / archive / new whitelist / whitelist offline). It is
        fire-and-forget: config returns OK quickly, then asynchronously
        re-assembles the snapshot and pushes to subscribers / sibling nodes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDynamicConfig(self, request, context):
        """GetDynamicConfig returns already-resolved config values for a user. The
        server internally runs GetExperimentResult(config_version) + gray + full
        release and merges per the resolution algorithm (design 03 §2.2). For
        external callers with no local cache.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStaticConfig(self, request, context):
        """GetStaticConfig returns the full-release value of each key (user-agnostic).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullAll': grpc.unary_unary_rpc_method_handler(
                    servicer.PullAll,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.PullAllRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.PullAllResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.SubscribeRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.ConfigUpdateEvent.SerializeToString,
            ),
            'ListNamespacesByKind': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespacesByKind,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListNamespacesByKindRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListNamespacesByKindResponse.SerializeToString,
            ),
            'ListConfigKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConfigKeys,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigKeysRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigKeysResponse.SerializeToString,
            ),
            'ListConfigVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConfigVersions,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigVersionsRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigVersionsResponse.SerializeToString,
            ),
            'NotifyBusinessNamespaceChange': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyBusinessNamespaceChange,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.NotifyBusinessNamespaceChangeRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.NotifyBusinessNamespaceChangeResponse.SerializeToString,
            ),
            'GetDynamicConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDynamicConfig,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetDynamicConfigRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetDynamicConfigResponse.SerializeToString,
            ),
            'GetStaticConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStaticConfig,
                    request_deserializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetStaticConfigRequest.FromString,
                    response_serializer=tipsy_dot_config_dot_v1_dot_config__pb2.GetStaticConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tipsy.config.v1.ConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tipsy.config.v1.ConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService(object):
    """ConfigService is the read entrypoint for business SDKs AND the abtest
    module. It carries:

    - PullAll / Subscribe:               business SDK ⇄ config (PullAll =
    synchronous full snapshot, Subscribe = server-streaming push of new
    snapshots when either business_snapshot_seq OR experiment_snapshot_seq
    advances).
    - ListNamespacesByKind / ListConfigKeys / ListConfigVersions: abtest
    module reads config metadata over gRPC (no cross-schema SQL).
    - NotifyBusinessNamespaceChange: abtest module signals config that an
    experiment / whitelist write happened ⇒ config bumps an in-memory
    experiment_snapshot_seq tracker, re-assembles the snapshot, pushes to
    local Subscribe streams, AND fans out NodeInternal.Notify to sibling
    config nodes. Fire-and-forget.

    See config-platform-backend.md §4.1 for the canonical contract; this proto
    is the source of truth for field tags and types.
    """

    @staticmethod
    def PullAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.config.v1.ConfigService/PullAll',
            tipsy_dot_config_dot_v1_dot_config__pb2.PullAllRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.PullAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tipsy.config.v1.ConfigService/Subscribe',
            tipsy_dot_config_dot_v1_dot_config__pb2.SubscribeRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.ConfigUpdateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespacesByKind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.config.v1.ConfigService/ListNamespacesByKind',
            tipsy_dot_config_dot_v1_dot_config__pb2.ListNamespacesByKindRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.ListNamespacesByKindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConfigKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.config.v1.ConfigService/ListConfigKeys',
            tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigKeysRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConfigVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.config.v1.ConfigService/ListConfigVersions',
            tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigVersionsRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.ListConfigVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyBusinessNamespaceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.config.v1.ConfigService/NotifyBusinessNamespaceChange',
            tipsy_dot_config_dot_v1_dot_config__pb2.NotifyBusinessNamespaceChangeRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.NotifyBusinessNamespaceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDynamicConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.config.v1.ConfigService/GetDynamicConfig',
            tipsy_dot_config_dot_v1_dot_config__pb2.GetDynamicConfigRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.GetDynamicConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStaticConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tipsy.config.v1.ConfigService/GetStaticConfig',
            tipsy_dot_config_dot_v1_dot_config__pb2.GetStaticConfigRequest.SerializeToString,
            tipsy_dot_config_dot_v1_dot_config__pb2.GetStaticConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
